// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wijhqrtcgsgjdicdicob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpamhxcnRjZ3NnamRpY2RpY29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDkwNzIsImV4cCI6MjA2MzU4NTA3Mn0.yq9myHcd5A8gGv70tzJWykKFxYSwW3ll3RaSFR9GBTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);